# Use root/example as user/password credentials
version:                    '3.1'

services:

  db:
    image:                  mariadb
    restart:                always
    environment:
      MYSQL_ROOT_PASSWORD:  Nogger123
      MYSQL_DATABASE:       dockerwp
      MYSQL_USER:           dockerwpuser
      MYSQL_PASSWORD:       Nogger123

  adminer:
    image:                  adminer
    restart:                always
    ports:
      - 80:80
